test:
    adapter:  mysql
    database:  
    username:  root
    password:  
    host:  localhost

development:
    adapter:  mysql
    database:  
    username:  root
    password:  
    host:  localhost

production:
    adapter:  mysql
    database:  
    username:  root
    password:  
    host:  localhost